### PR TITLE
Better readme and code. Maven project. Code styles. Copyright. Optionals. Null-safety. Expire Feature. Modularity. Nukkit Support. Unit Tests.

### LINKED ISSUE #1: [Feature] A timer.
There can be a timer for if player didn't say anything until XXX amounts of time runs `expired(Player)` method. For builder, `expireAfter(int)` method can be useful.

### LINKED ISSUE #2: [Feature] Maven project.
Maven/Gradle project would be good, in terms of easy usage.

### LINKED ISSUE #4: [Feature] Modularity for Bukkit/Spigot/Paper, Nukkit and others.
The project can separate for each minecraft server base system.

### LINKED ISSUE #5: [Feature] Unit tests.
Add some unit tests using Mockito.

### PR DESCRIPTION
**Pull request by portlek**
Done.
Fixes #2 
Fixes #1 
Fixes #4
Fixed #5

### CODE REVIEW

**Review by MrNemo64 — COMMENTED** [review]
I think this is a really cool change but this code is just too complex to me. If really like it but I need some time to understand it

**Comment by portlek** [comment]
> I think this is a really cool change but this code is just too complex to me. If really like it but I need some time to understand it

np, let it all hang out

**Comment by portlek** [comment]
you can look at here
https://github.com/portlek/player-inputs
what the general structure is
and what the changes are.

**Review by MrNemo64 — COMMENTED** [review]
I don't understand why you make everything final. Could you explain?

**Comment by portlek** [comment]
> I don't understand why you make everything final. Could you explain?

Sure. Because, immutability(finals) is decreasing the cohesion. and if you make your code less cohesion your project can run in every situation, everywhere. also this makes your code more testable.

**Comment by portlek** [comment]
you can read more information for the obj. cohesion here
https://www.yegor256.com/2020/02/11/object-cohesion.html
it can be helpful for your understanding.

**Comment by portlek** [comment]
also for the design this can be helpful
https://www.yegor256.com/2020/02/19/fat-skinny-design.html

**Comment by MrNemo64** [comment]
I'll check them

**Pull request closed without merging**
